version: '3'

services:
  db:
    image: postgres:14.0-alpine3.14
    environment:
      POSTGRES_PASSWORD: 'stan'
      POSTGRES_USER: 'stan'
      POSTGRES_DB: 'stan'
    ports:
      - 5432:5432

  back:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      target: base
    ports:
      - 4000:4000
    volumes:
      - ..:/workspace
    command: sleep infinity